## Analisis con el dataset limpio

### Cargar dataset limpio

In [5]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn

df = pd.read_csv("../dataset/stackoverflow_limpio.csv", index_col="question_id", parse_dates=["creation_date"])

In [6]:
df.head()

,programming_language,creation_date,view_count,score,answer_count,is_answered,has_accepted_answer,difficulty_score,quality_score
question_id,,,,,,,,,
79810291,python,2025-11-05 15:49:00,18,-1,0,False,False,0.200,0.70
79810195,python,2025-11-05 14:23:06,29,0,0,False,False,0.200,0.70
79810063,python,2025-11-05 12:42:01,27,2,0,False,False,0.201,0.70
79810057,python,2025-11-05 12:36:07,48,0,0,False,False,0.202,0.68
79810049,python,2025-11-05 12:28:43,44,1,0,False,False,0.199,0.70

### Cuantas preguntas hay por lenguaje

In [7]:
ax= df["programming_language"].value_counts() \
#     .plot(kind="bar", title="Preguntas por lengauje")

# ax.set_xlabel('Lenguaje')
# ax.set_ylabel('Count')

# plt.savefig("../graficos/01_preguntas_por_lenguaje.png", dpi=150)
# plt.show()

ax

programming_language
javascript    7353
python        6488
java          5945
c++           5272
c#            5166
swift         5043
r             5014
c             4868
rust          4847
ruby          4840
sql           4821
php           4812
go            4811
kotlin        4543
scala         4526
matlab        4155
typescript    4072
perl          3853
Name: count, dtype: int64

### Que lenguajes tienen mas vistas en promedio

In [8]:
ax = df.groupby("programming_language")["view_count"] \
    .mean() \
    .sort_values(ascending=False) \
    # .plot(kind="bar")

# ax.set_xlabel('Lenguaje')
# ax.set_ylabel('Numero de vistas')

# plt.savefig("../graficos/vistas_por_lenguaje.png", dpi=150)
# plt.show()

ax

programming_language
go            498.141135
ruby          492.813017
scala         355.513257
kotlin        322.103896
perl          316.172074
matlab        273.677738
rust          271.742315
php           258.705112
typescript    241.455059
swift         236.789808
python        203.948058
c++           180.828528
javascript    176.424861
java          176.083263
c             171.074569
c#            133.707123
sql           130.292470
r             105.397886
Name: view_count, dtype: float64

### Número de preguntas por el promedio de vistas de cada lengiuaje de programación

In [9]:
result = df.groupby("programming_language").agg({
    "programming_language" : "count",
    "view_count" : "mean"
}).rename(columns={"programming_language" : "num_preguntas", "view_count" : "promedio_vistas"})

result["preguntas_por_vista"] = result["num_preguntas"] / result["promedio_vistas"]

result = result.sort_values("preguntas_por_vista", ascending=False)

result

                      num_preguntas  promedio_vistas  preguntas_por_vista
programming_language
r                              5014       105.397886            47.572112
javascript                     7353       176.424861            41.677800
c#                             5166       133.707123            38.636685
sql                            4821       130.292470            37.001371
java                           5945       176.083263            33.762437
python                         6488       203.948058            31.812021
c++                            5272       180.828528            29.154692
c                              4868       171.074569            28.455428
swift                          5043       236.789808            21.297369
php                            4812       258.705112            18.600328
rust                           4847       271.742315            17.836751
typescript                     4072       241.455059            16.864422
matlab                         4155       273.677738            15.182090
kotlin                         4543       322.103896            14.104145
scala                          4526       355.513257            12.730890
perl                           3853       316.172074            12.186402
ruby                           4840       492.813017             9.821169
go                             4811       498.141135             9.657905

### Crecimiento de los lenguajes a los largo de los años

In [13]:
crecimiento = df.groupby([
            df["creation_date"].dt.year,
            "programming_language"
])["programming_language"].count().unstack()

crecimiento

programming_language,c,c#,c++,go,java,javascript,kotlin,matlab,perl,php,python,r,ruby,rust,scala,sql,swift,typescript
creation_date,,,,,,,,,,,,,,,,,,
2020,NaN,NaN,1.0,NaN,1.0,NaN,NaN,NaN,213.0,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021,15.0,3.0,31.0,NaN,9.0,8.0,NaN,699.0,1387.0,5.0,144.0,21.0,1.0,NaN,NaN,6.0,NaN,NaN
2022,26.0,7.0,46.0,NaN,190.0,38.0,NaN,1682.0,1118.0,4.0,349.0,24.0,1137.0,NaN,1776.0,36.0,2.0,NaN
2023,45.0,9.0,34.0,1745.0,174.0,78.0,NaN,1033.0,661.0,6.0,220.0,15.0,2331.0,245.0,1702.0,70.0,2.0,1.0
2024,2864.0,101.0,740.0,2472.0,466.0,1544.0,2833.0,563.0,341.0,2633.0,470.0,1829.0,1092.0,3384.0,824.0,2953.0,3037.0,1463.0
2025,1918.0,5046.0,4420.0,594.0,5105.0,5685.0,1710.0,178.0,133.0,2163.0,5303.0,3125.0,279.0,1218.0,224.0,1756.0,2002.0,2608.0

In [ ]:
## Parece que la mayoria de preguntas en los lenguajes surgen en los años 2024 y 2025, antes de eso, en varios lenguajes de programación las preguntas son muy reducidas, incluso en algunos casos ni siquiera hay preguntas

df.query('programming_language == "typescript"') \
        .groupby(df["creation_date"].dt.year) \
        ["programming_language"].count()

creation_date
2023       1
2024    1463
2025    2608
Name: programming_language, dtype: int64

In [22]:
crecimiento_ultimos_años = crecimiento.loc[[2024, 2025]]
crecimiento_ultimos_años

programming_language,c,c#,c++,go,java,javascript,kotlin,matlab,perl,php,python,r,ruby,rust,scala,sql,swift,typescript
creation_date,,,,,,,,,,,,,,,,,,
2024,2864.0,101.0,740.0,2472.0,466.0,1544.0,2833.0,563.0,341.0,2633.0,470.0,1829.0,1092.0,3384.0,824.0,2953.0,3037.0,1463.0
2025,1918.0,5046.0,4420.0,594.0,5105.0,5685.0,1710.0,178.0,133.0,2163.0,5303.0,3125.0,279.0,1218.0,224.0,1756.0,2002.0,2608.0

In [23]:
# crecimiento de 2024 a 2025

variacion = ((crecimiento_ultimos_años.loc[2025] - crecimiento_ultimos_años.loc[2024]) / crecimiento_ultimos_años.loc[2024] * 100).round(1)

variacion = variacion.sort_values(ascending=False)
variacion

programming_language
c#            4896.0
python        1028.3
java           995.5
c++            497.3
javascript     268.2
typescript      78.3
r               70.9
php            -17.9
c              -33.0
swift          -34.1
kotlin         -39.6
sql            -40.5
perl           -61.0
rust           -64.0
matlab         -68.4
scala          -72.8
ruby           -74.5
go             -76.0
dtype: float64